/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.twitter.to.kafka.twitter_to_kafka.kafka.model;

import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class TwitterAvroModel {
  private Long userId;
  private String id;
  private String text;
  private String createdAt;
}










